### Get tasks
GET https://todo-backend-qjfh.onrender.com/


### Add a new task
POST https://todo-backend-qjfh.onrender.com/new

Content-Type: application/json

{
  "description": "Test from Rest Client"
}

### Delete a task
DELETE https://todo-backend-qjfh.onrender.com/delete/:id
